#!/usr/bin/env python

import sys
import json
import requests

def post(url, data_path):
    with open(data_path) as data_file:
        data = json.load(data_file)
    headers = {'Content-type': 'application/json', 'Accept': 'text/plain'}
    res = requests.post(url, data=json.dumps(data), headers=headers)
    return res

if __name__ =='__main__':
    res = post(sys.argv[1], sys.argv[2])
    print res.text

