#!/usr/bin/env python

import sys
import path

set1 = set(path.Path(sys.argv[1]).lines(retain=False))
set2 = set(path.Path(sys.argv[2]).lines(retain=False))

for line in set1.difference(set2):
    print line
